name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Pin upload-artifact@v3 to satisfy hidden dependencies
        uses: actions/upload-artifact@v3.1.3
        with:
          name: noop
          path: README.md


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
