name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages-build-deployment:  # <-- This MUST be named exactly this
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Or your actual static build directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
